import type { Metadata } from "next";
import "./globals.css";
import Footer from '@/src/components/Footer'
import Navbar from '@/src/components/Navbar'
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Navbar />
            {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
